# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd698041d3322339ff3edf725129976264dbbaec4879c416e148fab507c02ecb7c85b8e85e6ffc8f9c1a0222893065100fd57247df9ee4d8490b37aff2f93fdb

test:
  secret_key_base: a81a2b95820fa489dfc043302723aa65135194b20dd7ba6ab9e4fb08e3e6abbd0fba52c5398e52960c3f1a441115bd00e376f409095c381b7157fe182ac6a833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
